### ISSUE TITLE
Is the website going to be hosted for public use?

### ISSUE THREAD

**Issue by WillTheDeveloper** [wonoly/www#15]
I noticed there is a domain but no website is active. When will it be going active?

**Comment by WillTheDeveloper** [comment]
Do you have some kind of roadmap or projects that we can look at to contribute?

**Comment by mauro-balades** [comment]
I am currently just finishing the user settings. When I finish the settings, I will start publishing @wonoly's products. All products will use the authentication system from this website meaning that no product will be available until I finish this site.

**Comment by mauro-balades** [comment]
> Do you have some kind of roadmap or projects that we can look at to contribute?

Currently, I don't have any roadmap. I will create one and feel free to contribute. :)

**Comment by WillTheDeveloper** [comment]
Why did you use third party packages to handle auth etc when Laravel has it as part of there ecosystem? I personally tend to use first party packages over third party where possible.

> Currently, I don't have any roadmap. I will create one and feel free to contribute. :)

Okay, close this issue when you have done it and I will start contributing.

**Comment by mauro-balades** [comment]
> Okay, close this issue when you have done it and I will start contributing.

:)

**Comment by WillTheDeveloper** [comment]
Roadmap has started to be created, issue is no longer required to be kept open.
