### ISSUE TITLE
[TODO] add a meta image 

### ISSUE THREAD

**Issue by mauro-balades** [wonoly/www#7]

**Comment by WillTheDeveloper** [comment]
Do you mean favicon? This can be added to the highest level layout that their is so it will appear across all the pages. I can do this if you want, but you need to have the image.

**Comment by WillTheDeveloper** [comment]
*Has to be an SVG*

**Comment by mauro-balades** [comment]
I mean, the image used for SEO and social apps such as fb

**Comment by WillTheDeveloper** [comment]
The little icon that shows on the browser window? It's a favicon. I think the same gets used for SEO.

**Comment by mauro-balades** [comment]
I mean the image wich can be defined as:
```html
<meta property="og:image" content="" ...
```

**Comment by WillTheDeveloper** [comment]
which*

Okie
