### ISSUE TITLE
[TODO] Update redirect URL for social logins when I get a domain

### ISSUE THREAD

**Issue by mauro-balades** [wonoly/www#9]

**Comment by WillTheDeveloper** [comment]
If you use relative links or the route method inside of your views then this will get updated automatically. Laravel will handle the absolute URL. More information on this is needed, doesn't entirely make sense for what you want to achieve by just having a title.

**Comment by mauro-balades** [comment]
I mean, URL for the redirect page for social logins such as github, they don't allow relative urls

**Comment by WillTheDeveloper** [comment]
I'm pretty sure there is a helper that will put it for you. But I get what you mean.
